### PR TITLE
New to GIT

### PR DESCRIPTION
**Pull request by LadyVii**
Adding some additional good energy to the mix :D

Hello I would like to expand the Welcome Page Quotes, I am noob to GIT, only learning today how to begin understanding its usage.

### CODE REVIEW

**Comment by LadyVii** [comment]
Thank you so much for the feedback, is there a page I can visit to provide instructions on how to add header rules, and redirect rules? I am completely noob to coding.

**Comment by wt** [comment]
How lovely. Can you please move the quotes into the data/quotes.toml in the form of that file.

Also, what kind of changes do you have in mind for the header rules and redirect rules?

Also, please sign off your diff. You can do the following to fix your commit and repush for this PR.

1. Rewrite commit including signoff in commit message: `git commit --amend -s`
2. Push change over your existing branch: `git push -f <push_repo> <local_branch>` (e.g. I would do `git push -f origin master` if I am pushing my master branch to my repo.

**Comment by wt** [comment]
Given that this PR hasn't been updated, I'm closing it.

**Comment by LadyVii** [comment]
Sorry! I have no prior experience, so I do not know what to do, I just
wanted to figure out how to add more quotes to the home page. Thank you for
all your help :)

**Pull request closed without merging**
